services:
  - type: web
    name: football-db-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3000
      - key: IMPORT_YEARS
        value: 10
      - key: DAILY_LOOKBACK_DAYS
        value: 14
