import { query } from '../db.js';

async function getLastMatches(teamId, beforeDate, limit = 5) {
  const sql = `
    SELECT * FROM matches
    WHERE match_date < $2
      AND status = 'finished'
      AND (home_team_id = $1 OR away_team_id = $1)
    ORDER BY match_date DESC
    LIMIT ${limit}
  `;
  const { rows } = await query(sql, [teamId, beforeDate]);
  return rows;
}

function average(values) {
  if (!values.length) return 0;
  return Number((values.reduce((a, b) => a + b, 0) / values.length).toFixed(2));
}

function extractStats(matches, teamId) {
  const goalsFor = [];
  const goalsAgainst = [];
  const cornersFor = [];
  const cardsFor = [];

  for (const m of matches) {
    const isHome = m.home_team_id === teamId;
    goalsFor.push(isHome ? (m.home_goals ?? 0) : (m.away_goals ?? 0));
    goalsAgainst.push(isHome ? (m.away_goals ?? 0) : (m.home_goals ?? 0));
    cornersFor.push(isHome ? (m.home_corners ?? 0) : (m.away_corners ?? 0));
    cardsFor.push(
      (isHome ? (m.home_yellow_cards ?? 0) + (m.home_red_cards ?? 0) : (m.away_yellow_cards ?? 0) + (m.away_red_cards ?? 0))
    );
  }

  return {
    goalsFor: average(goalsFor),
    goalsAgainst: average(goalsAgainst),
    cornersFor: average(cornersFor),
    cardsFor: average(cardsFor)
  };
}

export async function recalculateUpcomingFeatures(lookaheadDays = 7) {
  const { rows: upcoming } = await query(`
    SELECT id, match_date, home_team_id, away_team_id
    FROM matches
    WHERE match_date BETWEEN CURRENT_DATE AND CURRENT_DATE + $1::int
  `, [lookaheadDays]);

  for (const match of upcoming) {
    const homeLast = await getLastMatches(match.home_team_id, match.match_date);
    const awayLast = await getLastMatches(match.away_team_id, match.match_date);

    const home = extractStats(homeLast, match.home_team_id);
    const away = extractStats(awayLast, match.away_team_id);

    const expectedGoals = Number(((home.goalsFor + away.goalsFor + home.goalsAgainst + away.goalsAgainst) / 2).toFixed(2));
    const expectedCorners = Number((home.cornersFor + away.cornersFor).toFixed(2));
    const expectedCards = Number((home.cardsFor + away.cardsFor).toFixed(2));

    await query(`
      INSERT INTO team_match_features (
        match_id, home_last5_goals_for, home_last5_goals_against,
        away_last5_goals_for, away_last5_goals_against,
        home_last5_corners_for, away_last5_corners_for,
        home_last5_cards_for, away_last5_cards_for,
        expected_goals_line, expected_corners_line, expected_cards_line, updated_at
      ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NOW())
      ON CONFLICT (match_id) DO UPDATE SET
        home_last5_goals_for = EXCLUDED.home_last5_goals_for,
        home_last5_goals_against = EXCLUDED.home_last5_goals_against,
        away_last5_goals_for = EXCLUDED.away_last5_goals_for,
        away_last5_goals_against = EXCLUDED.away_last5_goals_against,
        home_last5_corners_for = EXCLUDED.home_last5_corners_for,
        away_last5_corners_for = EXCLUDED.away_last5_corners_for,
        home_last5_cards_for = EXCLUDED.home_last5_cards_for,
        away_last5_cards_for = EXCLUDED.away_last5_cards_for,
        expected_goals_line = EXCLUDED.expected_goals_line,
        expected_corners_line = EXCLUDED.expected_corners_line,
        expected_cards_line = EXCLUDED.expected_cards_line,
        updated_at = NOW()
    `, [
      match.id,
      home.goalsFor, home.goalsAgainst,
      away.goalsFor, away.goalsAgainst,
      home.cornersFor, away.cornersFor,
      home.cardsFor, away.cardsFor,
      expectedGoals, expectedCorners, expectedCards
    ]);

    const goalsMarket = expectedGoals >= 2.7 ? 'OVER_2_5' : expectedGoals >= 1.9 ? 'OVER_1_5' : 'UNDER_2_5';
    const cornersMarket = expectedCorners >= 10.5 ? 'OVER_9_5' : expectedCorners >= 9 ? 'OVER_8_5' : 'UNDER_9_5';
    const cardsMarket = expectedCards >= 5 ? 'OVER_4_5' : expectedCards >= 4 ? 'OVER_3_5' : 'UNDER_4_5';

    await query(`
      INSERT INTO predictions (match_id, market_goals, market_corners, market_cards, confidence_goals, confidence_corners, confidence_cards, notes, updated_at)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,NOW())
      ON CONFLICT (match_id) DO UPDATE SET
        market_goals = EXCLUDED.market_goals,
        market_corners = EXCLUDED.market_corners,
        market_cards = EXCLUDED.market_cards,
        confidence_goals = EXCLUDED.confidence_goals,
        confidence_corners = EXCLUDED.confidence_corners,
        confidence_cards = EXCLUDED.confidence_cards,
        notes = EXCLUDED.notes,
        updated_at = NOW()
    `, [
      match.id,
      goalsMarket,
      cornersMarket,
      cardsMarket,
      Math.min(95, 55 + expectedGoals * 10),
      Math.min(95, 50 + expectedCorners * 3),
      Math.min(95, 50 + expectedCards * 6),
      'Autogenerated from last 5 match averages stored in PostgreSQL only'
    ]);
  }
}
